### ISSUE TITLE
Propagating the shorthand to the autoloads

### ISSUE THREAD

**Issue by dickmao** [joaotavora/breadcrumb#3]
Should it get packaged, you'll need something like the below:

[patch.txt](https://github.com/joaotavora/breadcrumb/files/11468655/patch.txt)

**Comment by RuijieYu** [comment]
Thanks, but this doesn't belong here.  If able, you should send this patch to Emacs devs and let them decide.

**Comment by joaotavora** [comment]
Maybe the names of the autoloaded  functions should just be in longhand.

**Comment by joaotavora** [comment]
I fixed in this cda39e32f0d61de3ee471ecc5b1b1aa91214ab52 in the meantime.  But indeed a patch should be presented to Emacs.  

Anyway, @dickmao, my idea of that patch would not be not be to add `read-symbol-shothands` to the autoloads.el file, rather to add a modified  longhand version there.  But maybe this works too.

**Comment by joaotavora** [comment]
See https://debbugs.gnu.org/cgi/bugreport.cgi?bug=63480 for continued discussion on this.
